name = "notes-demo-worker"
type = "javascript"
workers_dev = true
compatibility_date = "2022-01-21"

[vars]
WORKERS_RS_VERSION = "0.0.7"
API_ORIGIN = "https://rora-notes-demo-api.herokuapp.com"

[build]
command = "cargo install -q worker-build && worker-build --release" # required

[build.upload]
dir = "build/worker"
format = "modules"
main = "./shim.mjs"

[[build.upload.rules]]
globs = ["**/*.wasm"]
type = "CompiledWasm"


# read more about configuring your Worker via wrangler.toml at:
# https://developers.cloudflare.com/workers/cli-wrangler/configuration
